---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8088}]
    - ["forwarded_port", {guest: 443, host: 5443}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[mediawiki::default]
    attributes:
